# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~

        square:
            quality: 75
            filters:
                thumbnail:
                    size: [100, 100]
                    mode: outbound

        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [460, 306]
                    mode: outbound

        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [600, 400]
                    mode: outbound
